//
//  UIAutomation.h
//  PublicAutomation
//
//  Created by Joe Masilotti on 11/20/14.
//  Copyright (c) 2014 ThoughtWorks. All rights reserved.
//

#import "UIAActionSheet.h"
#import "UIAActivityIndicator.h"
#import "UIAActivityView.h"
#import "UIAAlert.h"
#import "UIAApplication.h"
#import "UIAButton.h"
#import "UIACollectionCell.h"
#import "UIACollectionView.h"
#import "UIAEditingMenu.h"
#import "UIAElement.h"
#import "UIAElementArray.h"
#import "UIAElementNil.h"
#import "UIAElementSynonym.h"
#import "UIAHost.h"
#import "UIAImage.h"
#import "UIAKey.h"
#import "UIAKeyboard.h"
#import "UIALink.h"
#import "UIALocalizedValue.h"
#import "UIAMapView.h"
#import "UIANavigationBar.h"
#import "UIAPageIndicator.h"
#import "UIAPicker.h"
#import "UIAPickerWheel.h"
#import "UIAPopover.h"
#import "UIAProgressIndicator.h"
#import "UIARecorder.h"
#import "UIARecorderAction.h"
#import "UIARemote.h"
#import "UIAScreen.h"
#import "UIAScrollView.h"
#import "UIASearchBar.h"
#import "UIASecureTextField.h"
#import "UIASegmentedControl.h"
#import "UIASlider.h"
#import "UIAStaticText.h"
#import "UIAStatusBar.h"
#import "UIASwitch.h"
#import "UIASyntheticEvents.h"
#import "UIASyntheticStarkEvents.h"
#import "UIATabBar.h"
#import "UIATableCell.h"
#import "UIATableGroup.h"
#import "UIATableView.h"
#import "UIATarget.h"
#import "UIATextField.h"
#import "UIATextView.h"
#import "UIAToolbar.h"
#import "UIAWebView.h"
#import "UIAWindow.h"
#import "UIAXElement-Protocol.h"
#import "UIAXElement.h"
